# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cebb3c46d879b1c8b3cabb834c0ee0fecbbb835cd8c5ee4455623631c17d85eb289ae5ecef83c6a23d949f9c2c3e41c9ebd422b844a68b30d82e0b14c568c5c

test:
  secret_key_base: 680471591766515b96550c27e4350b73a44c269c95d35da581a3cfa3fd5377f763396db828acc27533fd715fa18d39b3f111a0570b5582549ed576e2b18ca276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
